const $=id=>document.getElementById(id);let chart=null;
const branches={Hợi:[4,4],Tý:[4,3],Sửu:[4,2],Dần:[4,1],Mão:[3,1],Thìn:[2,1],Tỵ:[1,1],Ngọ:[1,2],Mùi:[1,3],Thân:[1,4],Dậu:[2,4],Tuất:[3,4]};
const order=['Hợi','Tý','Sửu','Dần','Mão','Thìn','Tỵ','Ngọ','Mùi','Thân','Dậu','Tuất'];
const starH={"Tử vi":"tho","Liêm trinh":"hoa","Thiên đồng":"thuy","Vũ khúc":"kim","Thái Dương":"hoa","Thiên cơ":"moc","Thiên phủ":"tho","Thái âm":"thuy","Tham lang":"thuy","Cự môn":"thuy","Thiên tướng":"thuy","Thiên lương":"tho","Thất sát":"kim","Phá quân":"thuy","Hóa khoa":"kim","Hóa quyền":"hoa","Hóa lộc":"moc","Hóa kỵ":"thuy","Kình dương":"kim","Đà la":"kim","Địa không":"hoa","Địa kiếp":"hoa","Linh tinh":"hoa","Hỏa tinh":"hoa","Văn xương":"kim","Văn Khúc":"thuy","Thiên khôi":"hoa","Thiên việt":"hoa","Tả phù":"tho","Hữu bật":"thuy","Quốc ấn":"tho","Thiên hình":"hoa"};
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\':'&#92;','"':'&quot;'}[m]||m));
const norm=s=>String(s??'').trim().toLowerCase().replace(/\s+/g,' ');
const branchOf=p=>{const x=String(p?.dia_chi||p?.chi||p?.branch||'').trim();return order.find(b=>x===b||x.includes(b))||''};
const palaceByName=n=>Object.values(chart?.['12_cung']||{}).find(p=>norm(p?.cung)===norm(n));
function starChip(x,main=false){const n=x?.ten||x?.name||x?.sao||x;const nh=starH[n]||starH[Object.keys(starH).find(k=>norm(k)===norm(n))]||'';return `<span class="chip ${main?'main':''} ${nh?'nh-'+nh:''}">${esc(n)}</span>`}
function stars(list,main=false){return (list||[]).map(x=>starChip(x,main)).join('')||'<span class="meta">—</span>'}
function palaceHtml(p,branch){const pos=branches[branch];if(!pos)return '';if(!p)return `<div class="palace" style="grid-column:${pos[1]};grid-row:${pos[0]};opacity:.45"><div class="phead"><span class="pname">Địa Bàn</span><span class="branch">${branch}</span></div></div>`;const menh=norm(p.cung).includes('mệnh');return `<button class="palace ${menh?'menh':''}" style="grid-column:${pos[1]};grid-row:${pos[0]}" data-cung="${esc(p.cung||'')}"><div class="phead"><span class="pname">${esc(p.cung||'—')}${p.than_cu?'<small>THÂN CƯ</small>':''}</span><span class="branch">${branch}</span></div><div class="meta">${esc([p.can_chi,p.ngu_hanh,p.trang_sinh].filter(Boolean).join(' · '))}</div><div class="chips">${stars(p.chinh_tinh,true)}${stars(p.phu_tinh)}</div><div class="meta">${p.tuan?'Tuần ':''}${p.triet?'Triệt ':''}· Cung ${esc(p.cung_so||'—')}</div></button>`}
function renderDetail(p){if(!p){$('detail').classList.add('hidden');return}$('detail').classList.remove('hidden');$('detail').innerHTML=`<div class="card-head"><h2>${esc(p.cung||'Cung')}</h2><span>${esc(p.can_chi||'')} · ${esc(p.dia_chi||'')}</span></div><div class="summary-row"><span>Chính tinh</span><b>${(p.chinh_tinh||[]).map(x=>x?.ten||x?.name||x).join(', ')||'—'}</b></div><div class="summary-row"><span>Phụ tinh</span><b>${(p.phu_tinh||[]).map(x=>x?.ten||x?.name||x).join(', ')||'—'}</b></div><div class="summary-row"><span>Trạng thái</span><b>${esc(p.trang_sinh||'—')}</b></div>`}
function render(c){chart=c;const tb=c?.thien_ban||{};const arr=Object.values(c?.['12_cung']||{});const m=palaceByName('Mệnh');const matched=Array.isArray(c?.cach_cuc_analysis?.matched)?c.cach_cuc_analysis.matched:[];const mods=Array.isArray(c?.cach_cuc_analysis?.modifiers)?c.cach_cuc_analysis.modifiers:[];$('sMenh').textContent=branchOf(m)||'—';$('sBanMenh').textContent=tb.ban_menh||'—';$('sCuc').textContent=tb.ten_cuc||'—';$('sCach').textContent=matched.length+mods.length;$('cachBadge').textContent=matched.length+mods.length;$('cachCount').textContent=matched.length+mods.length;const by=new Map();arr.forEach(p=>{const b=branchOf(p);if(b&&!by.has(b))by.set(b,p)});$('board').innerHTML=order.map(b=>palaceHtml(by.get(b),b)).join('');document.querySelectorAll('.palace[data-cung]').forEach(el=>el.onclick=()=>renderDetail(palaceByName(el.dataset.cung)));$('summary').innerHTML=`<div class="summary-row"><span>Họ tên</span><b>${esc(tb.ten||'—')}</b></div><div class="summary-row"><span>Can-Chi năm</span><b>${esc([tb.can_nam,tb.chi_nam].filter(Boolean).join(' ')||'—')}</b></div><div class="summary-row"><span>Bản Mệnh</span><b>${esc(tb.ban_menh||'—')}</b></div><div class="summary-row"><span>Mệnh Cục</span><b>${esc(tb.ten_cuc||'—')}</b></div><div class="summary-row"><span>Mệnh Chủ</span><b>${esc(tb.menh_chu||'—')}</b></div><div class="summary-row"><span>Thân Chủ</span><b>${esc(tb.than_chu||'—')}</b></div>`;$('jsonBox').textContent=JSON.stringify(c,null,2);$('aiInfo').innerHTML=`<div class="summary-row"><span>12 cung</span><b>${arr.length}</b></div><div class="summary-row"><span>Địa Bàn</span><b>${by.size}/12</b></div><div class="summary-row"><span>Cách Cục</span><b>${matched.length+mods.length}</b></div><div class="summary-row"><span>Cung Mệnh</span><b>${esc(branchOf(m)||'—')}</b></div>`;renderCach();switchView('chart');}
function evidenceText(list){return Array.isArray(list)?list.map(ev=>{const rel=ev?.relation||ev?.relationship||'';const p=ev?.palace?.cung||ev?.palace?.dia_chi||ev?.cung||ev?.dia_chi||'';const s=Array.isArray(ev?.stars)?ev.stars.join(', '):(ev?.star||'');return [rel,p,s].filter(Boolean).join(' · ')}).filter(Boolean).join(' | '):''}
function renderCach(){const a=chart?.cach_cuc_analysis||{};const matched=Array.isArray(a.matched)?a.matched:[];const mods=Array.isArray(a.modifiers)?a.modifiers:[];const items=[];const seen=new Set();const add=(name,desc,cat,evi)=>{const k=norm(name);if(!k||seen.has(k))return;seen.add(k);items.push(`<article class="cach-item"><h3>${esc(name)}</h3>${cat?`<div class="cach-meta"><span class="tag">${esc(cat)}</span></div>`:''}<div>${esc(desc||'')}</div>${evi?`<div class="evidence"><b>Bằng chứng:</b> ${esc(evi)}</div>`:''}</article>`)};matched.forEach(x=>x&&add(x.name||'Cách Cục',x.description||x.reason||'',x.category||'Engine',evidenceText(x.matched_branches||[])));mods.forEach(x=>x&&add(x.name||'Cách Cục',x.interpretation||x.ai_instruction||'','Engine',evidenceText(x.breaking_evidence||[])));$('cachList').innerHTML=items.length?items.join(''):'<div class="empty">Chưa có Cách Cục được xác định.</div>'}
async function call(url,opt={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opt});const d=await r.json();if(!r.ok)throw Error(d.detail||'Request failed');return d}
function payload(){return{ngay:+$('day').value,thang:+$('month').value,nam:+$('year').value,gio_sinh:$('hour').value,gioi_tinh:$('gender').value,ten:$('name').value,duong_lich:$('calendar').value==='true',time_zone:+$('tz').value}}
async function lapSo(){const b=$('calcBtn');b.disabled=true;$('status').textContent='Đang lập lá số...';try{const d=await call('/api/lap-so',{method:'POST',body:JSON.stringify(payload())});render(d);$('status').textContent='Đã lập lá số';}catch(e){$('status').textContent=e.message}finally{b.disabled=false}}
function switchView(name){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id==='view-'+name));const titles={chart:'Thiên Bàn & 12 Địa Bàn',cach:'Cách Cục',ai:'AI luận giải',data:'Dữ liệu engine'};$('pageTitle').textContent=titles[name]||name}
async function askAI(){if(!chart)return;const q=$('question').value.trim();if(!q)return;$('askBtn').disabled=true;$('chat').insertAdjacentHTML('beforeend',`<div class="msg-bubble user"><small>Bạn</small>${esc(q)}</div><div id="typing" class="msg-bubble assistant"><small>AI Tử Vi</small>Đang luận giải...</div>`);$('question').value='';$('chat').scrollTop=$('chat').scrollHeight;try{const d=await call('/api/luan-giai',{method:'POST',body:JSON.stringify({...payload(),question:q,year:new Date().getFullYear()})});$('typing')?.remove();$('chat').insertAdjacentHTML('beforeend',`<div class="msg-bubble assistant"><small>AI Tử Vi</small>${esc(d.answer||'Chưa có phản hồi')}</div>`)}catch(e){$('typing')?.remove();$('chat').insertAdjacentHTML('beforeend',`<div class="msg-bubble assistant"><small>Lỗi</small>${esc(e.message)}</div>`)}finally{$('askBtn').disabled=false}}
function reset(){chart=null;$('status').textContent='';$('sMenh').textContent='—';$('sBanMenh').textContent='—';$('sCuc').textContent='—';$('sCach').textContent='0';$('cachBadge').textContent='0';$('cachCount').textContent='0';$('board').innerHTML='';$('summary').textContent='Chưa có dữ liệu.';$('cachList').innerHTML='<div class="empty">Chưa có Cách Cục được xác định.</div>';$('jsonBox').textContent='Chưa có dữ liệu.';$('aiInfo').textContent='Chưa có lá số.';$('chat').innerHTML='<div class="assistant msg-bubble"><small>AI Tử Vi</small>Hãy lập lá số rồi đặt câu hỏi.</div>';$('detail').classList.add('hidden')}
$('calcBtn').onclick=lapSo;$('resetBtn').onclick=reset;$('askBtn').onclick=askAI;document.querySelectorAll('.nav').forEach(b=>b.onclick=()=>switchView(b.dataset.view));$('question').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();askAI()}});
