export const $=id=>document.getElementById(id);
export const state={chart:null,lastAnswer:'',selectedPalace:null};
export const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\':'&#92;','"':'&quot;'}[m]||m));
export const norm=s=>String(s??'').trim().toLowerCase().replace(/\s+/g,' ');
export const call=async(url,opt={})=>{const r=await fetch(url,{headers:{'Content-Type':'application/json',...(opt.headers||{})},...opt});let d={};try{d=await r.json()}catch{}if(!r.ok)throw Error(d.detail||`HTTP ${r.status}`);return d};
export const profilePayload=()=>({ngay:+$('day').value||1,thang:+$('month').value||1,nam:+$('year').value||1996,gio_sinh:$('hour').value,gioi_tinh:$('gender').value,ten:$('name').value||'',duong_lich:$('calendar').value==='true',time_zone:+$('tz').value||7,nam_xem:Number($('viewYear').value)||new Date().getFullYear()});
export const branchOrder=['Hợi','Tý','Sửu','Dần','Mão','Thìn','Tỵ','Ngọ','Mùi','Thân','Dậu','Tuất'];
export const branchPos={Hợi:[4,4],Tý:[4,3],Sửu:[4,2],Dần:[4,1],Mão:[3,1],Thìn:[2,1],Tỵ:[1,1],Ngọ:[1,2],Mùi:[1,3],Thân:[1,4],Dậu:[2,4],Tuất:[3,4]};
export const branchOf=p=>{const x=String(p?.dia_chi||p?.chi||p?.branch||'').trim();return branchOrder.find(b=>x===b||x.includes(b))||''};
export const palaceByName=name=>Object.values(state.chart?.['12_cung']||{}).find(p=>norm(p?.cung)===norm(name));
export const starH={"Tử vi":"tho","Liêm trinh":"hoa","Thiên đồng":"thuy","Vũ khúc":"kim","Thái Dương":"hoa","Thiên cơ":"moc","Thiên phủ":"tho","Thái âm":"thuy","Tham lang":"thuy","Cự môn":"thuy","Thiên tướng":"thuy","Thiên lương":"tho","Thất sát":"kim","Phá quân":"thuy","Hóa khoa":"kim","Hóa quyền":"hoa","Hóa lộc":"moc","Hóa kỵ":"thuy","Kình dương":"kim","Đà la":"kim","Địa không":"hoa","Địa kiếp":"hoa","Linh tinh":"hoa","Hỏa tinh":"hoa","Văn xương":"kim","Văn Khúc":"thuy","Thiên khôi":"hoa","Thiên việt":"hoa","Tả phù":"tho","Hữu bật":"thuy","Quốc ấn":"tho","Thiên hình":"hoa"};
export const starName=x=>x?.ten||x?.name||x?.sao||x||'';
export const starsText=list=>(list||[]).map(starName).filter(Boolean).join(', ')||'—';
export const starChip=(x,main=false)=>{const n=starName(x);const nh=starH[n]||starH[Object.keys(starH).find(k=>norm(k)===norm(n))]||'';return `<span class="chip ${main?'main':''} ${nh?'nh-'+nh:''}">${esc(n)}</span>`};
export const stars=(list,main=false)=>(list||[]).map(x=>starChip(x,main)).join('')||'<span class="meta">—</span>';
