import {$,state,call,profilePayload,palaceByName} from './core.js';
import {refreshProfiles,saveCurrentProfile,loadProfile,clearProfilesUi} from './profile.js';
import {renderChart} from './chart.js';
import {showRelations} from './relations.js';
import {renderCach} from './cach.js';
import {renderVan10} from './van10.js';
import {askAI,runAudit} from './ai.js';

const titles={chart:'Thiên Bàn & 12 Địa Bàn',cach:'Cách Cục',relations:'Quan hệ cung',van10:'Vận 10 năm',ai:'AI luận giải',audit:'AI Audit',data:'Dữ liệu Engine'};
function switchView(name){document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view===name));document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===`view-${name}`));$('pageTitle').textContent=titles[name]||'TV AI'}
async function lapSo(){const b=$('calcBtn');b.disabled=true;$('status').textContent='Đang lập lá số...';try{const d=await call('/api/lap-so',{method:'POST',body:JSON.stringify(profilePayload())});state.chart=d;renderChart(d,p=>showRelations(p));renderCach();renderVan10();const m=palaceByName('Mệnh');$('aiInfo').innerHTML=`<div class="summary-row"><span>12 cung</span><b>${Object.keys(d?.['12_cung']||{}).length}</b></div><div class="summary-row"><span>Cung Mệnh</span><b>${m?.dia_chi||'—'}</b></div>`;saveCurrentProfile();$('status').textContent='Đã lập lá số';switchView('chart')}catch(e){$('status').textContent=e.message}finally{b.disabled=false}}
function reset(){state.chart=null;document.querySelectorAll('.view').forEach(x=>x.id==='view-chart'?x.classList.add('active'):x.classList.remove('active'));document.querySelectorAll('.nav').forEach(x=>x.classList.toggle('active',x.dataset.view==='chart'));$('pageTitle').textContent=titles.chart;$('board').innerHTML='';$('detail').classList.add('hidden');$('summary').textContent='Chưa có dữ liệu.';$('jsonBox').textContent='Chưa có dữ liệu.';$('van10Body').innerHTML='<tr><td colspan="6">Chưa có dữ liệu.</td></tr>';$('cachList').innerHTML='<div class="empty">Chưa có dữ liệu.</div>';$('auditResult').textContent='Chưa có bài luận.';$('chat').innerHTML='<div class="msg assistant"><small>AI Tử Vi</small>Hãy lập lá số rồi đặt câu hỏi.</div>';clearProfilesUi()}
window.addEventListener('DOMContentLoaded',()=>{refreshProfiles();$('viewYear').value=new Date().getFullYear();document.querySelectorAll('.nav').forEach(btn=>btn.onclick=()=>switchView(btn.dataset.view));$('calcBtn').onclick=lapSo;$('resetBtn').onclick=reset;$('profileSelect').onchange=e=>loadProfile(e.target.value);$('askBtn').onclick=askAI;$('runAuditBtn').onclick=runAudit;$('question').addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.isComposing){e.preventDefault();askAI()}});$('tocBtn').onclick=()=>{$('chat').scrollTo({top:0,behavior:'smooth'})}});
